name: Deploy to Tinybird

on:
  workflow_dispatch:
    inputs:
      target_job:
        type: choice
        description: Select the job to run
        options:
          - validate
          - deploy-staging
          - promote
  push:
    branches:
      - main
    paths:
      - 'tinybird/**'

jobs:
  validate:
    if: github.event.inputs.target_job == 'deploy-staging' || github.event.inputs.target_job == 'validate' 
    name: Validate Release
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    env:
      TINYBIRD_HOST: ${{ vars.TINYBIRD_HOST }}
      TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}

    defaults:
      run:
        working-directory: './tinybird'
    services:
      tinybird:
        image: tinybirdco/tinybird-local:latest
        ports:
          - 7181:7181
    steps:
      - uses: actions/checkout@v3
      - name: Install Tinybird CLI
        run: curl https://tinybird.co | sh

      - name: Build project
        run: |
          tb build

      - name: Run Tinybird tests
        run: |
          tb test run

    #  - name: Run Python tests
    #    run: |
    #      pip install pytest pyyaml
    #      PYTHONPATH=ree_data_tracker/src pytest ree_data_tracker/tests

      - name: Deployment check
        run: |
          tb --cloud --host ${{ env.TINYBIRD_HOST }} --token ${{ env.TINYBIRD_TOKEN }} deploy --check

  deploy-staging:
    if: github.event.inputs.target_job == 'deploy-staging'
    name: Deploy to Tinybird Staging
    needs: validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './tinybird'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Show diff between main and latest production deployment
        run: |
          # Find the latest tinybird-production-* tag
          LATEST_PROD_TAG=$(git tag --list 'tinybird-production-*' --sort=-creatordate | head -n 1)
          if [ -z "$LATEST_PROD_TAG" ]; then
            echo "No production deployment tag found."
            exit 0
          fi
          echo "🔍 Commits in main not in $LATEST_PROD_TAG (i.e., what will change in staging vs production):"
          git log $LATEST_PROD_TAG..origin/main --oneline

      - name: Install Tinybird CLI
        run: |
          curl https://tinybird.co | sh

      - name: Deploy to Tinybird Staging
        run: |
          tb --cloud --host ${{ env.TINYBIRD_HOST }} --token ${{ env.TINYBIRD_TOKEN }} deployment create

      - name: Tag repo with Tinybird Staging Deployment ID
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch --tags
          DEPLOYMENT_ID=$(tb --cloud --host ${{ env.TINYBIRD_HOST }} --token ${{ env.TINYBIRD_TOKEN }} deployment ls | awk '/Staging/ { print $2 }')
          if [ -z "$DEPLOYMENT_ID" ]; then
            echo "No deployment ID found, skipping tag."
            exit 0
          fi
          TAG="tinybird-staging-$DEPLOYMENT_ID"
          git tag "$TAG"
          git push origin "$TAG"

  promote:
    name: Promote to Tinybird Production
    if: github.event.inputs.target_job == 'promote'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './tinybird'
    steps:
      - uses: actions/checkout@v3

      - name: Install Tinybird CLI
        run: |
          curl https://tinybird.co | sh

      - name: Promote to Tinybird Production
        run: |
          # Get the list of deployments and look for any with status "Staging"
          STAGING_DEPLOYMENT=$(tb --cloud --cloud --host ${{ env.TINYBIRD_HOST }} --token ${{ env.TINYBIRD_TOKEN }} deployment ls | grep -i "Staging" || true)

          if [ -z "$STAGING_DEPLOYMENT" ]; then
            echo "✅ No staging deployment to promote."
          else
            echo "🚀 Staging deployment found. Promoting to production..."
            tb --cloud --host "${{ env.TINYBIRD_HOST }}" --token "${{ env.TINYBIRD_TOKEN }}" deployment promote
          fi

      - name: Tag repo with Tinybird Production Deployment ID
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch --tags
          DEPLOYMENT_ID=$(tb --cloud --host ${{ env.TINYBIRD_HOST }} --token ${{ env.TINYBIRD_TOKEN }} deployment ls | awk '/Production/ { print $2 }')
          if [ -z "$DEPLOYMENT_ID" ]; then
            echo "No deployment ID found, skipping tag."
            exit 0
          fi
          TAG="tinybird-production-$DEPLOYMENT_ID"
          git tag "$TAG"
          git push origin "$TAG"
