name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main
      - test
    paths:
      - 'supabase/migrations/**'
      - 'supabase/config.toml'
      - '.github/workflows/deploy-supabase-migrations.yml'

jobs:
  deploy:
    name: 'Deploy to Supabase'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ vars.SUPABASE_PROJECT_ID }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase db push
